### ISSUE TITLE
ProgressionΒarの作成

### ISSUE THREAD

**Issue by HIMA-HIMAZIN** [HIMA-HIMAZIN/webut-memo-app#10]
<img width="360" alt="スクリーンショット 2024-11-05 12 26 53" src="https://github.com/user-attachments/assets/5542b35f-0391-4678-a7cf-57a5d5f07ef9">

- [x] 済進行色：5DB53E
- [x] 未進行色：E7E7E7
- [x] 中間線　：9D9D9D

三画面で使用される予定です。
表示されている画面のリンクによって、色を変更させるようにしてください。

**Comment by Koutah15** [comment]
以下のように変更しました。
![Image](https://github.com/user-attachments/assets/848907ad-5513-4573-83fd-0809af3378df)
変更点
・Tailwind CSSを使って作成
・文字が済進行色になるように
