### ISSUE TITLE
ユーザー名作成画面のレイアウト作成

### ISSUE THREAD

**Issue by HIMA-HIMAZIN** [HIMA-HIMAZIN/webut-memo-app#20]
<img width="729" alt="スクリーンショット 2024-11-06 12 21 26" src="https://github.com/user-attachments/assets/a909941d-5790-49c3-bd69-7e5f3ba3bcb0">

- [ ] 左上にSvgのアイコンが存在すること
- [ ] 進行バーコンポーネントを使用すること
- [ ] GuideTitleコンポーネントを使用すること
- [ ] TextFieldを使用して、入力されたTextをuseStateで保持すること
- [ ] TextFieldの色はE7E7E7にすること

**Comment by Koutah15** [comment]
以下のような画面に変更しました。
![Image](https://github.com/user-attachments/assets/e0c0a454-495a-443d-a2a2-38dbd9da0b45)
変更点
テキスト入力部分をM以下のような画面に変更しました。
![Image](https://github.com/user-attachments/assets/e0c0a454-495a-443d-a2a2-38dbd9da0b45)
変更点
・ProgressionBerの変更
・テキスト入力部分をMaterial UIを採用しました。
