### ISSUE TITLE
プロフィールアイコンの作成ページ

### ISSUE THREAD

**Issue by Shvain** [HIMA-HIMAZIN/webut-memo-app#26]
## 要素
アイコンとなる画像をドロップするかファイルから参照してアイコンにしたい画像を挿入する。
もしくはプリセットから規定のアイコンを選択できる。

## タスク
- [x] ドロップゾーンの作成
- [x] アイコンプリセットを選択画面

**Comment by Koutah15** [comment]
以下のように変更しました。
![Image](https://github.com/user-attachments/assets/9acdb400-fa94-478e-92db-e49b47853ede)
変更点
・
