### ISSUE TITLE
１週間ごとにメモログのデータを削除する

### ISSUE THREAD

**Issue by Shvain** [HIMA-HIMAZIN/webut-memo-app#53]
## 要素
- supabase上から投稿されてから１週間経ったら削除するロジックの構築

**Comment by HIMA-HIMAZIN** [comment]
これもしかしたら参考になるかもしれないので貼っときます。
https://qiita.com/NoritakaTaniguchi/items/288b9264b5032325b4e4

**Comment by HIMA-HIMAZIN** [comment]
使えそう
https://infigate.net/supabase%E3%81%A7edge-functions%E3%82%92%E5%AE%9A%E6%9C%9F%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95/
